FROM debian:13.3-slim AS base

ARG USERNAME=developer
ARG USER_UID=1000
ARG USER_GID=1000

RUN if ! id -u ${USERNAME} >/dev/null 2>&1; then \
    groupadd --gid ${USER_GID} ${USERNAME} && \
    useradd --uid ${USER_UID} --gid ${USER_GID} -m ${USERNAME}; \
    fi \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
    ca-certificates \
    git \
    golang-go \
    sudo \
    && echo "${USERNAME} ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/90-${USERNAME} \
    && chmod 0440 /etc/sudoers.d/90-${USERNAME} \
    && rm -rf /var/lib/apt/lists/*

FROM base AS project

RUN apt-get update \
    && apt-get install -y --no-install-recommends restic \
    && rm -rf /var/lib/apt/lists/*

USER ${USERNAME}